# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hack/readme/login/login.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='hack/readme/login/login.proto',
    package='login',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\x1dhack/readme/login/login.proto\x12\x05login\".\n\x0cLoginRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1f\n\rLoginResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2G\n\x0fLeetcodeService\x12\x34\n\x05Login\x12\x13.login.LoginRequest\x1a\x14.login.LoginResponse\"\x00\x62\x06proto3')
)

_LOGINREQUEST = _descriptor.Descriptor(
    name='LoginRequest',
    full_name='login.LoginRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='name', full_name='login.LoginRequest.name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='password', full_name='login.LoginRequest.password', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=40,
    serialized_end=86,
)

_LOGINRESPONSE = _descriptor.Descriptor(
    name='LoginResponse',
    full_name='login.LoginResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='result', full_name='login.LoginResponse.result', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=88,
    serialized_end=119,
)

DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
    'DESCRIPTOR': _LOGINREQUEST,
    '__module__': 'hack.readme.login.login_pb2'
    # @@protoc_insertion_point(class_scope:login.LoginRequest)
})
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
    'DESCRIPTOR': _LOGINRESPONSE,
    '__module__': 'hack.readme.login.login_pb2'
    # @@protoc_insertion_point(class_scope:login.LoginResponse)
})
_sym_db.RegisterMessage(LoginResponse)

_LEETCODESERVICE = _descriptor.ServiceDescriptor(
    name='LeetcodeService',
    full_name='login.LeetcodeService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=121,
    serialized_end=192,
    methods=[
        _descriptor.MethodDescriptor(
            name='Login',
            full_name='login.LeetcodeService.Login',
            index=0,
            containing_service=None,
            input_type=_LOGINREQUEST,
            output_type=_LOGINRESPONSE,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_LEETCODESERVICE)

DESCRIPTOR.services_by_name['LeetcodeService'] = _LEETCODESERVICE

# @@protoc_insertion_point(module_scope)
