# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from hack.readme.login import login_pb2 as hack_dot_readme_dot_login_dot_login__pb2


class LeetcodeServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
            '/login.LeetcodeService/Login',
            request_serializer=hack_dot_readme_dot_login_dot_login__pb2.LoginRequest.SerializeToString,
            response_deserializer=hack_dot_readme_dot_login_dot_login__pb2.LoginResponse.FromString,
        )


class LeetcodeServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Login(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeetcodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Login': grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=hack_dot_readme_dot_login_dot_login__pb2.LoginRequest.FromString,
            response_serializer=hack_dot_readme_dot_login_dot_login__pb2.LoginResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'login.LeetcodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
